name: MDML Client Test
on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, deV ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9.13
    services:

      zookeeper:
        image: confluentinc/cp-zookeeper:6.1.1
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      broker:
        image: confluentinc/cp-kafka:6.1.1
        ports:
          - 9092:9092
          - 29092:29092
        env:
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_NUM_PARTITIONS: 10
          KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      schema-registry:
        image: confluentinc/cp-schema-registry:6.1.1
        ports:
          - 8081:8081
        env:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
          SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    
    steps:
      - uses: actions/checkout@v3
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Install mdml
        run: pip install mdml_client
      - name: Run test script
        run: pytest -s $GITHUB_WORKSPACE/tests/test_mdml_client.py
